# Generated by Django 3.0.3 on 2020-07-31 09:41

from django.db import migrations, models
import rekruter.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=30, verbose_name='first_name')),
                ('date_joined', models.DateTimeField(verbose_name='date joined')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('role_council', models.PositiveSmallIntegerField(choices=[(1, 'User minor'), (2, 'User Adult'), (3, 'User Adult Member'), (4, 'User Adult Council Member'), (5, 'Superuser')], default=1)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars')),
                ('gender', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'other'), (1, 'male'), (2, 'female')], null=True)),
                ('age', models.DateField()),
                ('mnemo_login', models.CharField(blank=True, max_length=11, unique=True, verbose_name='mnemo_login')),
                ('karma', models.IntegerField(default=0)),
                ('other_orientation', models.CharField(blank=True, max_length=30, verbose_name='other_orientation')),
                ('sex_role_activity', models.IntegerField(blank=True, null=True)),
                ('sex_role_dominance', models.IntegerField(blank=True, null=True)),
                ('alcohol', models.PositiveSmallIntegerField(choices=[(0, 'No drinking'), (1, "Doesn't mind company"), (2, 'Drinks alcohol'), (3, 'Drinks heavily')], null=True)),
                ('tobacco', models.PositiveSmallIntegerField(choices=[(0, 'No smoking'), (1, "Doesn't mind company"), (2, 'Smokes sometimes'), (3, 'Smokes heavily')], null=True)),
                ('other_drugs', models.CharField(blank=True, max_length=300, verbose_name='other_drugs')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='telephone')),
                ('other_contact', models.CharField(blank=True, max_length=300, verbose_name='other_contact')),
                ('about_me', models.CharField(blank=True, max_length=1500, verbose_name='other_contact')),
                ('interests', models.CharField(blank=True, max_length=500, verbose_name='other_contact')),
                ('showme_adultcontent', models.BooleanField(default=False, verbose_name='showme_adultcontent')),
                ('showmy_sexorientation', models.BooleanField(default=False, verbose_name='showmy_sexorientation')),
                ('showmy_sexrole', models.BooleanField(default=False, verbose_name='showmy_sexrole')),
                ('showme_commercial', models.BooleanField(default=True, verbose_name='showme_commercial')),
                ('showme_massevents', models.BooleanField(default=True, verbose_name='showme_massevents')),
                ('sendme_inv_status_me', models.BooleanField(default=True, verbose_name='sendme_inv_status_me')),
                ('sendme_inv_status_others', models.BooleanField(default=True, verbose_name='sendme_inv_status_others')),
                ('sendme_invitations', models.BooleanField(default=True, verbose_name='sendme_invitations')),
                ('sendme_friend_events', models.BooleanField(default=True, verbose_name='sendme_invitations')),
                ('sendme_join_request', models.BooleanField(default=True, verbose_name='sendme_invitations')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', rekruter.managers.UserManager()),
            ],
        ),
    ]
