# Generated by Django 3.0.3 on 2020-07-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekruter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='last_name',
            new_name='nickname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='album',
        ),
        migrations.RemoveField(
            model_name='user',
            name='building_no',
        ),
        migrations.RemoveField(
            model_name='user',
            name='citizenship',
        ),
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='dowod',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_hotel',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_translator',
        ),
        migrations.RemoveField(
            model_name='user',
            name='language',
        ),
        migrations.RemoveField(
            model_name='user',
            name='local_no',
        ),
        migrations.RemoveField(
            model_name='user',
            name='passport',
        ),
        migrations.RemoveField(
            model_name='user',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='user',
            name='quarter',
        ),
        migrations.RemoveField(
            model_name='user',
            name='street',
        ),
        migrations.RemoveField(
            model_name='user',
            name='telephone',
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='karma',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='mnemo_login',
            field=models.CharField(default=1, max_length=11, unique=True, verbose_name='mnemo_login'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='role_council',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'User minor'), (2, 'User Adult'), (3, 'User Adult Member'), (4, 'User Adult Council Member'), (5, 'Superuser')], default=1, null=True),
        ),
    ]
