# Generated by Django 3.0.3 on 2020-07-31 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekruter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='karma',
            new_name='experience',
        ),
        migrations.AlterField(
            model_name='user',
            name='sex_role_activity',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex_role_dominance',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
