# Generated by Django 3.0.3 on 2020-08-02 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekruter', '0002_auto_20200731_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='avatar',
            new_name='avatar1',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar2',
            field=models.ImageField(blank=True, null=True, upload_to='avatars'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar3',
            field=models.ImageField(blank=True, null=True, upload_to='avatars'),
        ),
    ]
