# Generated by Django 3.0.3 on 2020-08-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekruter', '0003_auto_20200802_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_adult',
            field=models.BooleanField(default=False, verbose_name='staff status'),
        ),
    ]
