# Generated by Django 3.0.3 on 2020-08-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekruter', '0004_user_is_adult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_adult',
            field=models.BooleanField(default=False, verbose_name='is adult'),
        ),
    ]
