# Generated by Django 3.0.3 on 2020-07-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekruter', '0004_auto_20200730_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(verbose_name='date joined'),
        ),
    ]
