# Generated by Django 3.0.3 on 2020-08-03 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekruter', '0005_auto_20200803_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_adult',
        ),
        migrations.AlterField(
            model_name='user',
            name='about_me',
            field=models.CharField(blank=True, max_length=1500, verbose_name='about_me'),
        ),
        migrations.AlterField(
            model_name='user',
            name='interests',
            field=models.CharField(blank=True, max_length=500, verbose_name='interests'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role_council',
            field=models.PositiveSmallIntegerField(choices=[(1, 'User Regular'), (2, 'User Member'), (3, 'User Council Member'), (4, 'Superuser')], default=1),
        ),
    ]
