# Generated by Django 3.0.3 on 2020-08-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekruter', '0008_auto_20200803_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex_preference',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Brak'), (1, 'Straight'), (2, 'Gay'), (3, 'Bi'), (4, 'Trans'), (5, 'Other')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex_role_activity',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Brak'), (1, 'Pasywny'), (4, 'Raczej Pasywny'), (3, 'Zmienny'), (4, 'Raczej Aktywny'), (5, 'Aktywny')], default=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex_role_dominance',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Brak'), (1, 'Uległy'), (2, 'Raczej Uległy'), (3, 'Neutralny'), (4, 'Raczej Dominujący'), (5, 'Dominujący')], default=3),
        ),
    ]
