# Generated by Django 3.0.3 on 2020-08-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekruter', '0009_auto_20200804_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex_role_activity',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Brak'), (1, 'Pasywny'), (4, 'Raczej Pasywny'), (3, 'Zmienny'), (4, 'Raczej Aktywny'), (5, 'Aktywny')], default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex_role_dominance',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Brak'), (1, 'Uległy'), (2, 'Raczej Uległy'), (3, 'Neutralny'), (4, 'Raczej Dominujący'), (5, 'Dominujący')], default=0),
        ),
    ]
