# Generated by Django 3.0.3 on 2020-08-09 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('body', models.CharField(blank=True, max_length=1500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('datefrom', models.DateTimeField(blank=True, null=True)),
                ('dateto', models.DateTimeField(blank=True, null=True)),
                ('is_commercial', models.BooleanField(default=False)),
                ('is_mass_event', models.BooleanField(default=False)),
                ('is_adult_only', models.BooleanField(default=False)),
                ('is_alcohol', models.BooleanField(default=False)),
                ('is_tobacco', models.BooleanField(default=False)),
                ('other_drugs', models.CharField(max_length=300)),
                ('is_sex_party', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('sex_preference', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Brak'), (1, 'Straight'), (2, 'Gay'), (3, 'Bi'), (4, 'Trans'), (5, 'Other')], null=True)),
                ('sex_role_activity', models.PositiveSmallIntegerField(choices=[(0, 'Brak'), (1, 'Pasywny'), (4, 'Raczej Pasywny'), (3, 'Zmienny'), (4, 'Raczej Aktywny'), (5, 'Aktywny')], default=0)),
                ('sex_role_dominance', models.PositiveSmallIntegerField(choices=[(0, 'Brak'), (1, 'Uległy'), (2, 'Raczej Uległy'), (3, 'Neutralny'), (4, 'Raczej Dominujący'), (5, 'Dominujący')], default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-datefrom'],
            },
        ),
    ]
