# Generated by Django 3.1 on 2020-09-29 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('title_pl', models.CharField(max_length=150, null=True)),
                ('title_en', models.CharField(max_length=150, null=True)),
                ('body', models.CharField(blank=True, max_length=1500, null=True)),
                ('body_pl', models.CharField(blank=True, max_length=1500, null=True)),
                ('body_en', models.CharField(blank=True, max_length=1500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('datefrom', models.DateTimeField(blank=True, null=True)),
                ('dateto', models.DateTimeField(blank=True, null=True)),
                ('is_commercial', models.BooleanField(default=False)),
                ('is_mass_event', models.BooleanField(default=False)),
                ('is_adult_only', models.BooleanField(default=False)),
                ('is_alcohol', models.BooleanField(default=False)),
                ('is_tobacco', models.BooleanField(default=False)),
                ('other_drugs', models.CharField(blank=True, max_length=300, null=True)),
                ('other_drugs_pl', models.CharField(blank=True, max_length=300, null=True)),
                ('other_drugs_en', models.CharField(blank=True, max_length=300, null=True)),
                ('is_sex_party', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_for_straight', models.BooleanField(default=False)),
                ('is_for_gay', models.BooleanField(default=False)),
                ('is_for_bi', models.BooleanField(default=False)),
                ('is_for_trans', models.BooleanField(default=False)),
                ('is_for_other', models.BooleanField(default=False)),
                ('is_for_passive', models.BooleanField(default=False)),
                ('is_for_r_passive', models.BooleanField(default=False)),
                ('is_for_switch', models.BooleanField(default=False)),
                ('is_for_r_active', models.BooleanField(default=False)),
                ('is_for_active', models.BooleanField(default=False)),
                ('is_for_submisive', models.BooleanField(default=False)),
                ('is_for_r_submissive', models.BooleanField(default=False)),
                ('is_for_neutral', models.BooleanField(default=False)),
                ('is_for_r_dominant', models.BooleanField(default=False)),
                ('is_for_dominant', models.BooleanField(default=False)),
                ('other_preferences', models.CharField(blank=True, max_length=300, null=True)),
                ('other_preferences_pl', models.CharField(blank=True, max_length=300, null=True)),
                ('other_preferences_en', models.CharField(blank=True, max_length=300, null=True)),
                ('pubdate', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-datefrom'],
            },
        ),
        migrations.CreateModel(
            name='EventsMenuNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintitle', models.CharField(max_length=50)),
                ('maintitle_pl', models.CharField(max_length=50, null=True)),
                ('maintitle_en', models.CharField(max_length=50, null=True)),
                ('new_event', models.CharField(max_length=50)),
                ('new_event_pl', models.CharField(max_length=50, null=True)),
                ('new_event_en', models.CharField(max_length=50, null=True)),
                ('my_events', models.CharField(max_length=50)),
                ('my_events_pl', models.CharField(max_length=50, null=True)),
                ('my_events_en', models.CharField(max_length=50, null=True)),
                ('edit_event', models.CharField(max_length=50)),
                ('edit_event_pl', models.CharField(max_length=50, null=True)),
                ('edit_event_en', models.CharField(max_length=50, null=True)),
                ('search_events', models.CharField(max_length=50)),
                ('search_events_pl', models.CharField(max_length=50, null=True)),
                ('search_events_en', models.CharField(max_length=50, null=True)),
                ('my_templates', models.CharField(max_length=50)),
                ('my_templates_pl', models.CharField(max_length=50, null=True)),
                ('my_templates_en', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'EventsMenuNames',
            },
        ),
        migrations.CreateModel(
            name='PartyDivider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('title_pl', models.CharField(max_length=150, null=True)),
                ('title_en', models.CharField(max_length=150, null=True)),
                ('descr', models.CharField(blank=True, max_length=500, null=True)),
                ('descr_pl', models.CharField(blank=True, max_length=500, null=True)),
                ('descr_en', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('title_pl', models.CharField(max_length=50, null=True)),
                ('title_en', models.CharField(max_length=50, null=True)),
                ('descr', models.CharField(blank=True, max_length=500, null=True)),
                ('descr_pl', models.CharField(blank=True, max_length=500, null=True)),
                ('descr_en', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
            options={
                'verbose_name_plural': 'Taxes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TaxPanel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('title_pl', models.CharField(max_length=50, null=True)),
                ('title_en', models.CharField(max_length=50, null=True)),
                ('descr', models.CharField(blank=True, max_length=200, null=True)),
                ('descr_pl', models.CharField(blank=True, max_length=200, null=True)),
                ('descr_en', models.CharField(blank=True, max_length=200, null=True)),
                ('tax_type', models.PositiveSmallIntegerField(choices=[(0, 'i'), (1, 'lub'), (2, 'opcjonalnie'), (3, 'każdy')], default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('title_pl', models.CharField(max_length=150, null=True)),
                ('title_en', models.CharField(max_length=150, null=True)),
                ('role_descr', models.CharField(blank=True, max_length=600, null=True)),
                ('role_descr_pl', models.CharField(blank=True, max_length=600, null=True)),
                ('role_descr_en', models.CharField(blank=True, max_length=600, null=True)),
                ('alt_user', models.CharField(blank=True, max_length=150, null=True)),
                ('tax_free', models.BooleanField(default=False)),
                ('aux_coordinator', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
