# Generated by Django 3.0.3 on 2020-08-09 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imprezownia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='other_preferences',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='sex_preference',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Brak'), (1, 'Straight'), (2, 'Gay'), (3, 'Bi'), (4, 'Trans'), (5, 'Other')], default=0),
        ),
    ]
