# Generated by Django 3.1 on 2020-09-29 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('imprezownia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userrole',
            name='from_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imprezownia.partydivider'),
        ),
        migrations.AddField(
            model_name='taxpanel',
            name='from_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imprezownia.event'),
        ),
        migrations.AddField(
            model_name='tax',
            name='from_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imprezownia.taxpanel'),
        ),
        migrations.AddField(
            model_name='partydivider',
            name='from_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imprezownia.event'),
        ),
        migrations.AddField(
            model_name='event',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
