# Generated by Django 3.1 on 2020-08-29 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imprezownia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='pubdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
