# Generated by Django 3.1 on 2020-09-05 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imprezownia', '0002_event_pubdate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partydivider',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='tax',
            options={'ordering': ['id'], 'verbose_name_plural': 'Taxes'},
        ),
        migrations.AlterModelOptions(
            name='taxpanel',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='userrole',
            options={'ordering': ['id']},
        ),
    ]
