# Generated by Django 3.1 on 2020-09-29 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imprezownia', '0003_auto_20200929_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='from_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imprezownia.partydivider'),
        ),
    ]
