# Generated by Django 3.0.3 on 2020-08-02 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0004_auto_20200802_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilenames',
            name='avatar',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profilenames',
            name='avatar_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profilenames',
            name='avatar_pl',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
