# Generated by Django 3.0.3 on 2020-08-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0005_auto_20200802_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilenames',
            name='mnemo_explanation',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='profilenames',
            name='mnemo_explanation_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='profilenames',
            name='mnemo_explanation_pl',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='profilenames',
            name='mnemo_login',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profilenames',
            name='mnemo_login_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profilenames',
            name='mnemo_login_pl',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
