# Generated by Django 3.0.3 on 2020-08-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0006_auto_20200803_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilenames',
            name='age_explaination',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='profilenames',
            name='age_explaination_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='profilenames',
            name='age_explaination_pl',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
