# Generated by Django 3.0.3 on 2020-08-03 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0007_auto_20200803_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilenames',
            old_name='age_explaination',
            new_name='age_explanation',
        ),
        migrations.RenameField(
            model_name='profilenames',
            old_name='age_explaination_en',
            new_name='age_explanation_en',
        ),
        migrations.RenameField(
            model_name='profilenames',
            old_name='age_explaination_pl',
            new_name='age_explanation_pl',
        ),
    ]
