# Generated by Django 3.0.3 on 2020-08-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0009_auto_20200803_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilenames',
            name='other_preference',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profilenames',
            name='other_preference_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profilenames',
            name='other_preference_pl',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
