# Generated by Django 3.0.3 on 2020-08-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0010_auto_20200803_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilenames',
            name='bi',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profilenames',
            name='bi_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profilenames',
            name='bi_pl',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profilenames',
            name='gay',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profilenames',
            name='gay_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profilenames',
            name='gay_pl',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profilenames',
            name='other',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profilenames',
            name='other_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profilenames',
            name='other_pl',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profilenames',
            name='rather',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profilenames',
            name='rather_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profilenames',
            name='rather_pl',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profilenames',
            name='straight',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profilenames',
            name='straight_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profilenames',
            name='straight_pl',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profilenames',
            name='switch',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profilenames',
            name='switch_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profilenames',
            name='switch_pl',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profilenames',
            name='trans',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profilenames',
            name='trans_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profilenames',
            name='trans_pl',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
