# Generated by Django 3.0.3 on 2020-08-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0014_auto_20200804_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilenames',
            name='underage_warning',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='profilenames',
            name='underage_warning_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='profilenames',
            name='underage_warning_pl',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
