# Generated by Django 3.0.3 on 2020-08-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0015_auto_20200805_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilenames',
            name='myprofiledelete',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profilenames',
            name='myprofiledelete_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profilenames',
            name='myprofiledelete_pl',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profilenames',
            name='profiledelete_explain',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='profilenames',
            name='profiledelete_explain_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='profilenames',
            name='profiledelete_explain_pl',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
