# Generated by Django 3.1 on 2020-08-29 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0017_auto_20200809_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageskin',
            name='eventimagedefault',
            field=models.ImageField(blank=True, null=True, upload_to='skins'),
        ),
    ]
