# Generated by Django 3.1 on 2020-09-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0018_pageskin_eventimagedefault'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageskin',
            name='userimagedefault',
            field=models.ImageField(blank=True, null=True, upload_to='skins'),
        ),
    ]
